### ISSUE TITLE
Set deploy config to be updatable/deletable by default for CI/CD success

### ISSUE THREAD

**Issue by SilentRhetoric** [algorandfoundation/algokit-beaker-default-template#28]
Setting the HelloWorldApp delete & update parameters to `is_local` and `on_update` behavior to be dependent on the network on which it is deployed (`UpdateApp` locally but `Fail` on any other network) creates an unintuitive foot-gun for developers new to AlgoKit.  

This is because the default behavior will work smoothly on the Localnet but then sets the developer up for the GH Actions workflow to fail the first time an updated contract is pushed to GH.  

The automated deploy-testnet job will attempt to update the testnet contact, but it will have defaulted to being non-updatable/deletable unless the developer has thought to reconfigure this:  

```deploy_response = app_client.deploy(
                on_schema_break=(
                    OnSchemaBreak.ReplaceApp if is_local else OnSchemaBreak.Fail
                ),
                on_update=OnUpdate.UpdateApp if is_local else OnUpdate.Fail,
                allow_delete=is_local,
                allow_update=is_local,
            )
```

To something like:

```
deploy_response = app_client.deploy(
                on_schema_break=(
                    OnSchemaBreak.ReplaceApp
                ),
                on_update=OnUpdate.UpdateApp,
                allow_delete=True,
                allow_update=True,
            )
```

I think this would both better demonstrate the idempotent deployment approach harmoniously with the automated CI/CD and also be a reasonably good practice for production smart contract development until the developer makes a conscious decision to have the contract be permanent and/or immutable.

**Comment by daniel-makerx** [comment]
This was resolved by using the AppendApp action instead of Fail when in higher environments see [here](https://github.com/algorandfoundation/algokit-beaker-default-template/blob/main/template_content/smart_contracts/%7B%7B%20contract_name%20%7D%7D/%7B%25%20if%20deployment_language%20%3D%3D%20'python'%20%25%7Ddeploy_config.py%7B%25%20endif%20%25%7D.jinja#L38)
